sudo: required
language: java
jdk:
  -openjdk8

# script: mvn clean install -DskipTests

services: 
  - docker
  
befor_install: 
  - mvn clean install -DskipTests
  - docker build -t my-order-ms .
  
#script: 
#    - docker run my-order-ms
