apiVersion: apps/v1
kind: Deployment                          # type of object we are creating, here we are creating of type "Deployment"
metadata:                                 # Details about above Object - "Deployment"
  name:   auth-server-deployment              # name of above object - "Deployment"


spec:                                     # specification of "Deployment" object 
  replicas: 1                             # 3 pods will be created by "Deployment" config
  
  selector: 
    matchLabels:
      component: auth-server-ms        # key to match with pod -> line number: 17 
  
  template:                               # template is the configuration of pods - Pod Template 
    
    metadata: 
      labels: 
        component: auth-server-ms     # key to map with "Service" object -> prod -> product
    
    spec:                                 # specification of Pod
      containers:                         #container configuration
        - name: auth-server-container
          image: ravisaditya/auth-server
          ports: 
            - containerPort: 8822
                
   
        
      