apiVersion: apps/v1
kind: Deployment                          # type of object we are creating, here we are creating of type "Deployment"
metadata:                                 # Details about above Object - "Deployment"
  name:   orderms-deployment              # name of above object - "Deployment"


spec:                                     # specification of "Deployment" object 
  replicas: 1                            # 3 pods will be created by "Deployment" config
  
  selector: 
    matchLabels:
      component: order-ms       # key to match with pod -> line number: 18
  
  template:                               # template is the configuration of pods - Pod Template 
    
    metadata: 
      labels: 
        component: order-ms     # key to map with "Service" object
    
    spec:                                 # specification of Pod
    
      # volumes:
      #   - name: ms-storage
      #     persistentVolumeClaim:
      #       claimName: persistent-volume-claim
     
      containers:                         #container configuration
        - name: orderms-container
          image: ravisaditya/orderms
          ports: 
            - containerPort: 8002 
            
          # volumeMounts:
          #   - name: ms-storage
          #     mountPath: /var/storage
              
#          env: 
#            - name: DB-PASSWORD
#              valueFrom: 
#                secretKeyRef: 
#                  name: db-password
#                  key: db_pass
#                  
#            - name: OKTA-API-KEY
#              valueFrom: 
#                secretKeyRef: 
#                  name: okta-api-key
#                  key: okt_api_key
                
                
   
        
      