apiVersion: apps/v1
kind: Deployment                          # type of object we are creating, here we are creating of type "Deployment"
metadata:                                 # Details about above Object - "Deployment"
  name:   orderms-deployment              # name of above object - "Deployment"

#specification of "Deployment" object
spec: 
  replicas: 3                             # 3 pods will be created by "Deployment" config
  selector: 
    matchLabels:
      component: microservice-order       # key to match with pod